@Clients.Api_HostAddress = http://localhost:8080

POST http://localhost:8080/clients/
Accept: application/json
Content-Type: application/json

{
  "name": "John Doe",
  "email": "JohnSmithte@random.com",
  "membership": "Premium",
  "BirthDate": "1990-01-01"
}

###


GET http://localhost:8080/clients/0bf94ab1-506e-457d-975a-2b048adbc1bb
Accept: application/json

###

GET http://localhost:8080/clients/
Accept: application/json

###
